services:

  postgres:
    image: postgres:15
    container_name: event_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: event_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin123@postgres:5432/event_db"

  event-service:
    build: ./event-service
    ports:
      - "8002:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin123@postgres:5432/event_db"

  registration-service:
    build: ./registration-service
    ports:
      - "8003:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin123@postgres:5432/event_db"
      EVENT_SERVICE_URL: "https://event-service.ambitiousmeadow-e7af242d.southeastasia.azurecontainerapps.io"

  notification-service:
    build: ./notification-service
    ports:
      - "8004:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin123@postgres:5432/event_db"

volumes:
  postgres_data: