name: CI - Auth Service

on:
push:
branches:
- main

env:
IMAGE_NAME: auth-service

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Login to ACR
    run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

  - name: Build Docker Image
    run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest ./auth-service

  - name: Push Docker Image
    run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
```
